name: Schema bypass

on:
  workflow_dispatch:
    inputs:
      hash:
        type: string
        description: 'hash of the config'
        required: true
jobs:
  schema_check_job:
    runs-on: ubuntu-latest
    name: A job to check schema
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: schema-check
        uses: VitaliiBorodii/schema_bypass_test@v0.1.4
        with:
          token: ${{secrets.INIGO_TOKEN}}
          apiUrl: https://de2e-213-110-151-104.ngrok-free.app/query
          hash: ${{github.event.inputs.hash}}
      - run: | 
          echo schema bypass result: ${{ steps.schema-check.outputs.result }}
        shell: bash