name: Schema check

on: [push]

jobs:
  schema_check_job:
    runs-on: ubuntu-latest
    name: A job to check schema
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: schema-check
        uses: VitaliiBorodii/schema_check_test@v1.2.6
        with:
          token: ${{secrets.INIGO_TOKEN}}
          apiUrl: https://de2e-213-110-151-104.ngrok-free.app/query
          configs: ./configs/*.yml
      - run: | 
          echo schema check result: ${{ steps.schema-check.outputs.result }}
        shell: bash