name: Schema check

on: [push]

jobs:
  schema_check_job:
    runs-on: ubuntu-latest
    name: A job to check schema
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: VitaliiBorodii/schema_check_test@v1.0.2
        with:
          token: '123'
      - run: echo result ${{ steps.foo.outputs }}
        shell: bash