name: Schema check

on: [push]

jobs:
  schema_check_job:
    runs-on: ubuntu-latest
    name: A job to check schema
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: schema-check
        uses: VitaliiBorodii/schema_check_test@v1.2.6
        with:
          token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOm51bGwsInRva2VuVHlwZSI6InVzZXJfdG9rZW4iLCJ1c2VyX3Byb2ZpbGUiOiJhZG1pbiIsInVzZXJfcm9sZXMiOlsiYWRtaW4iLCJjb25maWd1cmF0b3IiLCJ2aWV3ZXIiLCJndWVzdCJdLCJ1c2VyX2lkIjoxLCJ1c2VyX25hbWUiOiJnZW9yZ2VAbHVjYXMuY29tIiwib3JnX2lkIjoxLCJ0b2tlbiI6ImY0Y2FjMTg1LWFhN2UtNGUxNy04NmM5LWJkOWI0Y2JlOWY1ZSIsImV4cCI6MTY5ODM5ODAyMSwiaWF0IjoxNjk3NzkzMjIxfQ.5o_dpS3HlZytJwcqLkTQop4WtHL1MibKh6dSDu9YZSQXSQr6bQUbkSntYfm_9r2g2McumdAJ0vOIJoPwN2jPgw
          apiUrl: https://de2e-213-110-151-104.ngrok-free.app/query
          configs: ./configs/*.yml
      - run: | 
          echo schema check result: ${{ steps.schema-check.outputs.result }}
        shell: bash