name: Schema check

on: [push]

jobs:
  schema_check_job:
    runs-on: ubuntu-latest
    name: A job to check schema
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: schema-check
        uses: VitaliiBorodii/schema_check_test@v1.2.5
        with:
          token: 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOm51bGwsInRva2VuVHlwZSI6InVzZXJfdG9rZW4iLCJ1c2VyX3Byb2ZpbGUiOiJ1c2VyIiwidXNlcl9yb2xlcyI6WyJhZG1pbiIsImNvbmZpZ3VyYXRvciIsInZpZXdlciIsImd1ZXN0Il0sInVzZXJfaWQiOjEsInVzZXJfbmFtZSI6Imdlb3JnZUBsdWNhcy5jb20iLCJvcmdfaWQiOjEsInRva2VuIjoiMjJmNzUzYzItNjZhMS00NjA2LWIzODAtZjM5ZTE5ZjMyOWVkIiwiZXhwIjoxNjk4MjU5MTA1LCJpYXQiOjE2OTc2NTQzMDV9.Y3vvvO5wQUdI-T0sG65kNgy0YeCHwDdbI3JkMQ0oYdQRHszt-KIMKSEnGJewefB9cxP1st3eax3s47hNuQhkbQ'
          configs: ./configs/*.yml
          apiUrl: https://dev.inigo.io/api/query
      - run: | 
          echo schema check result: ${{ steps.schema-check.outputs.result }}
        shell: bash