name: Schema check

on: [push]

jobs:
  schema_check_job:
    runs-on: ubuntu-latest
    name: A job to check schema
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: schema-check
        uses: VitaliiBorodii/schema_check_test@v1.1.3
        with:
          token: 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOm51bGwsInRva2VuVHlwZSI6InVzZXJfdG9rZW4iLCJ1c2VyX3Byb2ZpbGUiOiJ1c2VyIiwidXNlcl9yb2xlcyI6WyJhZG1pbiIsImNvbmZpZ3VyYXRvciIsInZpZXdlciIsImd1ZXN0Il0sInVzZXJfaWQiOjEsInVzZXJfbmFtZSI6Imdlb3JnZUBsdWNhcy5jb20iLCJvcmdfaWQiOjEsInRva2VuIjoiY2RhNGI5OWEtMDFjYy00NGY5LWI4NGMtYzc4YzNlMWRmNjljIiwiZXhwIjoxNjk3NjE4NTc0LCJpYXQiOjE2OTcwMTM3NzR9.NjwjUZyEOnbXeSF0jQYtloQXgXW7FeGoBfsDqjbdLhCubwaoXlkqJXcluyhUG6D_K87-Zx6ba0UBESzQsww22Q'
          configs: ./configs/*.yml
          apiUrl: https://dev.inigo.io/api/query
      - run: | 
          echo schema check result: ${{ steps.schema-check.outputs.result }}
        shell: bash